### PR TITLE
image upload system from abiola fakorede

### PR DESCRIPTION
**Pull request by Fakorede**
This is the image upload i created with PHP. Tested and working. Will try to convert to an api once i can get a charging source for my PC.

### CODE REVIEW

**Review by osatoojo — CHANGES_REQUESTED** [review]
there are some errors with your code

**Comment by Fakorede** [comment]
Sorry, I don't think u have tested it otherwise point out the errors.

**Comment by osatoojo** [comment]
the logic we are working with is.....upload a file and save to temp and then a permanent folder. I have tested. It is left to you to tell me if there is a folder i should have created to store the images. We are on the same team

**Comment by Fakorede** [comment]
Yeah. The images will save to an "uploads" folder on line 28. The code is fine.

**Pull request merged**
